name: updateCsvcubedPackage
on:
  # repository_dispatch:
  #   types: [on-demand-test]
  push:
    branches:
      - 'MuazzamChaud/issue527'

jobs: 
  updating_csvcubed_packge:
    name: updating_csvcubed_packge
    runs-on: ubuntu-latest 
    steps:
      - name: Checking csvcubed pypi package version
        run: |
            sudo apt-get update 
            sudo apt-get install jq
            pythonPackage=csvcubed;curl -Ls https://pypi.org/pypi/$pythonPackage/json || declare -x VERSION=$(jq -r '.version' package.json)
            echo "package.json version is $VERSION"
  
      - name: Creating new branch 'csvcubed_package_update'
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'csvcubed_package_update'
          sha: '${{ github.event.pull_request.head.sha }}'
      
      # - name: Updating csvcubed pypi package version to latest
      # - name: creating PR for new branch 'csvcubed_package_update'