name: updateCsvcubedPackage
on: 
 workflow_dispatch:
#   push:
#     branches:
#       - 'MuazzamChaud/issue527'

jobs: 
  updating_csvcubed_packge:
    name: updating_csvcubed_packge
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout files 2
        run: git clone 'https://csvcubed:${{ secrets.CSVCUBED_GIT_COMMIT_TOKEN }}@github.com/GSS-Cogs/gss-utils.git' --depth 1

      - name: Checking contents of pyproject.toml
        run: | 
          CURRENT_CSVCUBED_VERSION=$(sed -n 's/^ *csvcubed\s*=.*"\([^"]*\)".*/\1/p' pyproject.toml)
          echo "Csvcubed version: $CURRENT_CSVCUBED_VERSION"
          echo "CURRENT_CSVCUBED_VERSION=$CURRENT_CSVCUBED_VERSION" >> $GITHUB_ENV

      - name: Checking csvcubed pypi package version
        run: |
            sudo apt-get update 
            sudo apt-get install jq
            pythonPackage=csvcubed;curl -Ls https://pypi.org/pypi/$pythonPackage/json >> package.json
            LATEST_VERSION=$(curl -s https://pypi.org/pypi/$pythonPackage/json | jq -r .info.version)
            echo "Latest package version is: $LATEST_VERSION"
            echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
            
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: creating new branch and updating csvcubed
        run: |
          if [ ${{ env.CURRENT_CSVCUBED_VERSION }} != ${{ env.LATEST_VERSION }} ]
          then

            python3 -m ensurepip
            python3 -m pip install --upgrade pip
            python3 -m pip install poetry
            git checkout "master"
            git checkout -b "csvcubed_package_update_${{ env.LATEST_VERSION }}"

            git config --global user.email "csvcubed@gsscogs.uk"
            git config --global user.name "csvcubed Version Updater"

            
            sed -i 's/^csvcubed =.*$/csvcubed = "${{ env.LATEST_VERSION }}"/g' pyproject.toml
            poetry lock --no-update

            git add pyproject.toml poetry.lock
            git commit -m "Updating csvcubed to ${{ env.LATEST_VERSION }}"
            git push --set-upstream origin "csvcubed_package_update_${{ env.LATEST_VERSION }}" 

          fi
     
      - name: creating PR for new branch
        run: gh pr create -t "Updating csvcubed pacakage to ${{ env.LATEST_VERSION }}" -b "This branch has the csvcubed package updated to version ${{ env.LATEST_VERSION }}" -H "csvcubed_package_update_${{ env.LATEST_VERSION }}" -B "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
