name: updateCsvcubedPackage
on:
  # repository_dispatch:
  #   types: [on-demand-test]
  push:
    branches:
      - 'MuazzamChaud/issue527'

jobs:
  runs-on: ubuntu-latest  
  check_dep:
    name: Check python requirements file and update
    steps:
      - name: Checkout
        run: |
            apt-get install -y jq
            pythonPackage=csvcubed;curl -Ls https://pypi.org/pypi/$pythonPackage/json | declare -x VERSION=$(jq -r .info.version)
            echo "package.json version is $VERSION"
  updating_csvcubed_packge:
    name: Create branch to hold new updated csvcubed package
    steps:
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'csvcubed_package_update'
        sha: '${{ github.event.pull_request.head.sha }}'